# Generated by Django 6.0.4 on 2026-04-17 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('assignment_type', models.CharField(choices=[('test', 'Test'), ('written', 'Yozma ish'), ('file', 'Fayl topshiriq')], max_length=20, verbose_name='Tur')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif/Savol matni')),
                ('instructions', models.TextField(blank=True, verbose_name="Ko'rsatmalar")),
                ('deadline', models.DateTimeField(verbose_name='Topshirish muddati')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa, test uchun)')),
                ('max_score', models.FloatField(default=100.0, verbose_name='Maksimal ball')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('closed', 'Yopilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Savollarni aralashtirish')),
                ('questions_per_student', models.PositiveIntegerField(default=0, verbose_name='Har talabaga necha savol (0=barchasi)')),
                ('allowed_file_types', models.JSONField(default=list, help_text='Masalan: [".pdf", ".docx"]', verbose_name='Ruxsat etilgan fayl turlari')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='Maks fayl hajmi (MB)')),
                ('ai_syllabus_score', models.FloatField(blank=True, null=True, verbose_name='AI sillabus baho')),
                ('ai_syllabus_feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='assignments', to='core.group', verbose_name='Guruhlar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('syllabus_check', 'Sillabus tekshiruvi'), ('auto_grading', 'Avtomatik baholash'), ('accessibility', 'Inklyuziv tekshiruv')], max_length=30)),
                ('result', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='assessment.assignment')),
            ],
            options={
                'verbose_name': 'AI jurnal',
                'verbose_name_plural': 'AI jurnal yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('success', 'Muvaffaqiyat'), ('error', 'Xato')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('text_html', models.TextField(blank=True, verbose_name='HTML format (formula/rasm uchun)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Rasm')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Mavzu')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('option_a', models.TextField(verbose_name='A variant')),
                ('option_b', models.TextField(verbose_name='B variant')),
                ('option_c', models.TextField(verbose_name='C variant')),
                ('option_d', models.TextField(blank=True, verbose_name='D variant (ixtiyoriy)')),
                ('is_accessible', models.BooleanField(default=True, help_text="Ko'zi ojiz talabalar uchun ovozli o'qilishi mumkinmi", verbose_name='TTS uchun mos')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assignment', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Topshirildi'), ('graded', 'Baholandi'), ('disputed', 'Shikoyat')], default='submitted', max_length=20)),
                ('test_answers', models.JSONField(default=dict)),
                ('text_answer', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('suspicious_events', models.JSONField(default=list)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_graded_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('teacher_note', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Shikoyat matni')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('answered', 'Javob berildi'), ('escalated', 'Kafedra mudiriga yuborildi'), ('closed', 'Yopildi')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assessment.submission')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submission_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assessment.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabi/', verbose_name='Fayl (PDF/DOCX)')),
                ('topics', models.JSONField(default=list, verbose_name="Mavzular ro'yxati")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='core.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Sillabus',
                'verbose_name_plural': 'Syllabuslar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
