# Generated by Django 6.0.4 on 2026-04-17 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bank nomi')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savol banki',
                'verbose_name_plural': 'Savol banklari',
                'ordering': ['-updated_at'],
                'unique_together': {('teacher', 'subject', 'title')},
            },
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_questions/')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Mavzu')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='medium', max_length=10)),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Takroriy savol (AI)')),
                ('duplicate_note', models.CharField(blank=True, max_length=200)),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan marta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='assessment.questionbank')),
            ],
            options={
                'verbose_name': 'Bank savoli',
                'verbose_name_plural': 'Bank savollari',
                'ordering': ['-created_at'],
            },
        ),
    ]
