# Generated by Django 6.0.4 on 2026-04-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Savol soni')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_quotas', to='assessment.assignment')),
            ],
            options={
                'verbose_name': 'Mavzu kvotasi',
                'verbose_name_plural': 'Mavzu kvotalari',
                'unique_together': {('assignment', 'topic')},
            },
        ),
    ]
