# Generated by Django 6.0.4 on 2026-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_topic_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_improvements',
            field=models.JSONField(blank=True, default=list, verbose_name='AI: yaxshilash kerak'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list, verbose_name='AI: kuchli tomonlar'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_syllabus_fb',
            field=models.TextField(blank=True, verbose_name='AI sillabus izohi'),
        ),
    ]
