# Generated by Django 6.0.4 on 2026-04-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_ai_detailed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='A variant rasmi'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='B variant rasmi'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='C variant rasmi'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/', verbose_name='D variant rasmi'),
        ),
    ]
