# Generated by Django 6.0.4 on 2026-04-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_difficulty_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='appeal_reason',
            field=models.TextField(blank=True, verbose_name="E'tiroz sababi"),
        ),
        migrations.AddField(
            model_name='submission',
            name='appeal_response',
            field=models.TextField(blank=True, verbose_name="O'qituvchi javobi"),
        ),
        migrations.AddField(
            model_name='submission',
            name='appeal_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('pending', "Ko'rib chiqilmoqda"), ('reviewing', 'Qayta tekshirilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='none', max_length=20, verbose_name="E'tiroz holati"),
        ),
        migrations.AddField(
            model_name='submission',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
