# Generated by Django 4.2.30 on 2026-05-12 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0007_submission_appeal_reason_submission_appeal_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, help_text="Bo'sh qoldirilsa — guruhdagi barcha talabalar", limit_choices_to={'role': 'talaba'}, related_name='allowed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Tanlangan talabalar'),
        ),
    ]