# Generated by Django 4.2.30 on 2026-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assignment_allowed_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='show_review_to_student',
            field=models.BooleanField(default=False, help_text="Belgilangan bo'lsa, talaba natija sahifasida o'ziga tushgan savollarni va o'z javoblarini ko'radi (to'g'ri javoblar yashirin)", verbose_name="Talabaga savollar tahlilini ko'rsatish"),
        ),
    ]