# Generated by Django 6.0.4 on 2026-04-17 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kafedra nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('year', models.PositiveSmallIntegerField(default=1, verbose_name="O'quv yili")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=20, verbose_name='Fan kodi')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Kreditlar')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Semestr')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(verbose_name='Imtihon sanasi va vaqti')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Davomiyligi (daqiqa)')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.department', verbose_name='Kafedra')),
                ('groups', models.ManyToManyField(related_name='exam_schedules', to='core.group', verbose_name='Guruhlar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='core.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Imtihon jadvali',
                'verbose_name_plural': 'Imtihon jadvallari',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='subject_teachers', to='core.group', verbose_name='Guruhlar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='core.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Fan biriktirish',
                'verbose_name_plural': 'Fan biriktirmalar',
                'unique_together': {('subject', 'teacher')},
            },
        ),
    ]
