# Generated by Django 4.2.30 on 2026-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_submission_appeal_reason_submission_appeal_response_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='exams', to='assessment.assignment', verbose_name='Topshiriqlar'),
        ),
    ]