# Generated by Django 6.0.4 on 2026-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram botdan /start bosib olingan ID', max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
